### ISSUE TITLE
Social Links(Twitter, FB,Github) and Email id for Competitive coding wings Members and Coordinators

### ISSUE THREAD

**Issue by BelieveC** [GeekHaven/profiletemplates#7]

**Comment by satylogin** [comment]
https://www.facebook.com/satyarth.agrahari
https://github.com/satylogin
iec2015018@iiita.ac.in

**Comment by rohan2962** [comment]
https://www.facebook.com/rohan.m.rayaraddi
https://github.com/rohan2962
iit2015032@iiita.ac.in
